name: EconPlugin
version: 1.0
main: com.anthony.Econ
api-version: 1.21
description: A simple economy plugin for managing player currency
authors: [ Anthony ]


permissions:
  econplugin.save.use:
    description: Allows a player to save their own balance
    default: true

  econplugin.save.others:
    description: Allows an admin to save other players' balances
    default: op

  econplugin.balance.use:
    description: Allows a player to view their own balance
    default: true

  econplugin.balance.others:
    description: Allows an admin to view other players' balances
    default: op
